### ISSUE TITLE
add `method` to jpeg-recompress options

### ISSUE THREAD

**Issue by ramiroaraujo** [toy/image_optim#102]
jpeg-recompress has a few compression methods, being `ssim` the default one. Yet, `smallfry` usually get much better results, and it's the same algorithm JPEGMini uses. The author warns that it might be patented in the future, but as of now it's usable. It would be great to add the `--method` option for jpeg-compress to allow to chose it :)
I'll try to PR it myself if I find the time

**Comment by ramiroaraujo** [comment]
jpeg-recompress has a few compression methods, being `ssim` the default one. Yet, `smallfry` usually get much better results, and it's the same algorithm JPEGMini uses. The author warns that it might be patented in the future, but as of now it's usable. It would be great to add the `--method` option for jpeg-compress to allow to chose it :)
I'll try to PR it myself if I find the time

**Comment by toy** [comment]
Great, thanks, I'll get to it unless you will find the time for it faster :)
