### ISSUE TITLE
How to install image_optim on Ubuntu?

### ISSUE THREAD

**Issue by confile** [toy/image_optim#104]
According to the readme I did: 

```
sudo apt-get install -y advancecomp gifsicle jhead jpegoptim libjpeg-progs optipng pngcrush pngquant
```

Then I tried: ``image_optim`` but I get: 

```
-bash: image_optim: command not found
```

1. Is there anything else I have to do on ubuntu?
2. Do I have to install additional tools like pngout on ubuntu? If yes how do I set the path for them on ubuntu?

@toy  You help is appreciated.

**Comment by toy** [comment]
```sh
gem install image_optim image_optim_pack
```
You man need to prefix the command with `sudo`.

**Comment by confile** [comment]
Why do I have to use this: 

```
sudo apt-get install -y advancecomp gifsicle jhead jpegoptim libjpeg-progs optipng pngcrush pngquant
```

**Comment by toy** [comment]
There is a section [Binaries pack](https://github.com/toy/image_optim#binaries-pack) just before [Linux - Debian/Ubuntu](https://github.com/toy/image_optim#linux---debianubuntu), so the easiest way to install nearly all tolls is to use `image_optim_pack`, but all of them can be also installed manually. I've already created #98 to make readme clearer, like telling in every installing section to first check `image_optim_pack`. I'm near the point when I will have time for this.

**Comment by confile** [comment]
Is there any way to skip png optimization?

**Comment by toy** [comment]
Depends on usage: using command line tool or `ImageOptim` interface you can pass only non png images, otherwise disabling all png optimizers (you can check by running `image_optim --info`).

**Comment by confile** [comment]
Thanks
