### ISSUE TITLE
Optimized images are too big

### ISSUE THREAD

**Issue by confile** [toy/image_optim#105]
I tried a lot of jpg image to optimize with ``image_optim``. 

It reduces the size but when I compare how the results of what facebook does are, these images are way smaller than what comes out from image_optim. 

Is there a way to decrease the image size any further without reducing the quality?

**Comment by toy** [comment]
By default `image_optim` is lossless, so using all the tools it will only remove all unnecessary data and will try to optimise compression. But you can allow lossy optimisations using `allow_lossy: true` / `--allow-lossy`, and if not enough with default options, configure workers to reduce image size more like `jpegrecompress: {quality: 0}` / `--jpegrecompress-quality=0`.

As a small test I've uploaded a 2048×1536 941KB image to facebook and got same size 324KB image, using `image_optim --allow-lossy --jpegrecompress-quality=0` I've got a 220KB image.
Visual difference in my case was hardly noticeable.
Comparing original vs optimised using imagemagick: mean error per pixel (normalized mean error, normalized peak error)
for facebook optimisation: 5.29145e+09 (0.000184438, 0.203922)
for image_optim: 5.96241e+09 (0.000240838, 0.262745)

The jpegrecompress worker will soon get more options like #103, so more flexibility to get the desired result.

**Comment by confile** [comment]
That is great thank you.
