### ISSUE TITLE
Dragonfly integration

### ISSUE THREAD

**Issue by ahmgeek** [toy/image_optim#107]
What about integrate it with Dragonfly ?

**Comment by ahmgeek** [comment]
@markevans

**Comment by toy** [comment]
First thought I had — is it really a good idea as optimising images is not a very fast process (especially for png images). Otherwise it should be easy to implement:
```ruby
image_optim = ImageOptim.new
Dragonfly.app.configure do
  processor :image_optim do |content, *args|
    optimized = image_optim.optimize_image_data(content.data)
    content.update(optimized) if optimized
  end
end
```
Not tested, I just wrote it from documentation, also it maybe better to manipulate files instead of data.

**Comment by markevans** [comment]
@ahmgeek great to use it with dragonfly but I won't be integrating things like that into core - rather I'd encourage people to write custom processors/plugins as separate libraries, or just do a quick processor like @toy suggested

**Comment by ahmgeek** [comment]
@toy @markevans thanks fellas, let it be a plugin, I've already used it as a custom processor though.
