### ISSUE TITLE
Describe nice level better

### ISSUE THREAD

**Issue by toy** [toy/image_optim#140]

**Comment by razvanmitre** [comment]
What is nice level?

**Comment by toy** [comment]
@razvanmitre Level of "niceness" of process, the higher the nicer, so how "nice" to all other processes it will be. Higher value mean less resources compared to other processes. From testing and according to wikipedia, it can be in the range -19..20, and only super user can set it to negative values.

**Comment by razvanmitre** [comment]
Thanks!
