### ISSUE TITLE
APNG are convented to static PNG

### ISSUE THREAD

**Issue by rogomantik** [toy/image_optim#142]
The conversion removes all but 1st frame

**Comment by toy** [comment]
I've released new version 1.5.0 of [`image_size`](/toy/image_size) which includes [detection of apng](/toy/image_size/commit/f0db49c9603934b76bd6ec1f317d93a8eb28ef27), which should make image_optim ignore apng images. I will also update dependency so `image_optim` requires new `image_size`.

Adding support for optimising apng images is a separate issue, as most or all used png tools don't support properly optimising them.

**Comment by toy** [comment]
Please reopen if needed.
