### ISSUE TITLE
Add number of colors option for pngquant

### ISSUE THREAD

**Issue by nosideeffects** [toy/image_optim#144]
`pngquant` allows you to pass in a number of colors to quantize images with a maximum allowed palette size.

**Comment by toy** [comment]
Do you mean the `--posterize` flag?

**Comment by nosideeffects** [comment]
That is different than what I meant, but that would be useful, too.

The command is `pngquant [options] [ncolors] -- pngfile`. For instance, in my current workflow, I produce many small icons, so it is safe for me to limit the colors to 16. Without the option to specify the colors, I must use `pngquant` separately before using `image_optim`.

**Comment by toy** [comment]
Ah, you are right! I thought that I remembered an option for number of colours, but did not find it in the list of pngquant flags.
Should be easily doable then.

**Comment by toy** [comment]
@nosideeffects Please have a look at [pngquant-max-colors](https://github.com/toy/image_optim/compare/pngquant-max-colors) branch

**Comment by nosideeffects** [comment]
Looks good to me!
