### ISSUE TITLE
[Enhancement] Better SVG support

### ISSUE THREAD

**Issue by brian-kephart** [toy/image_optim#156]
First, thanks a lot for this tool, it's made my life easier.

Currently the only tool in the mix for optimizing SVGs is SVGO. Instructions for this library require a global NPM installation which is difficult in some environments (Heroku, in my case). I haven't yet been able to make this tool work without installing it globally.

It seems like there should be another tool for SVGs ([maybe this?](https://github.com/RazrFalcon/svgcleaner/tree/786e8087f47e3e662fcb92066f0947a182241244)), or alternate instructions for installing SVGO non-globally.

**Comment by toy** [comment]
I'm glad that it is helpful :)

About svgo – I saw a great idea in ImageOptim.app to pack svgo into a single shell script and bundle the result.

About svgcleaner – looks interesting, plus there is a comparison with scour which can also be an alternative.

**Comment by brian-kephart** [comment]
Thanks for the response. I'm not really concerned about having multiple tools, though I suppose it wouldn't hurt. One tool is fine if I can install it in my production environment. The alternative tool suggestion was just in case SVGO couldn't be made to work.

Is [this](https://github.com/ImageOptim/ImageOptim/commit/6c0a90182a03940d60417a7f981b98932633ba12#diff-e2cd4546aa9ecbb8359416e286a61738) the SVGO bundle you were referring to?

**Comment by brian-kephart** [comment]
After some experiments, I found that:
1. The other utilities I tried didn’t reduce file size as much as SVGO.
2. Using SVGO non-globally was really easy once I figured it out.

I’ll submit a PR updating the README with alternate instructions.
