### ISSUE TITLE
GPU vs CPU

### ISSUE THREAD

**Issue by mdenissov** [toy/image_optim#160]
Which tools use GPU instead of CPU to processing images? May GPU decrease processing time?

**Comment by toy** [comment]
I don't remember any mentions of GPU related to any of the tools, but it may be worth verifying that. Maybe there a version of the tools that use GPU to increase performance.

**Comment by mdenissov** [comment]
@toy Thank you for the answer! image_optim is very useful tool.

**Comment by toy** [comment]
Thanks for feedback 😉
