### ISSUE TITLE
`advpng` installed on ubuntu, or OS X via homebrew, _does not_ have a proper version number

### ISSUE THREAD

**Issue by jayroh** [toy/image_optim#165]
On a recent install of ubuntu, installing `advancecomp` provides the advpng binary. However, when running `advpng -V` it returns unexpected output:

```sh
advpng -V
advancecomp vnone by Andrea Mazzoleni, http://www.advancemame.it
```

This causes the bin resolver to bail, when there's no proper version number

```ruby
when :advpng, :gifsicle, :jpegoptim, :optipng
  capture("#{escaped_path} --version 2> #{Path::NULL}")[/\d+(\.\d+)+/]
```

Happy to provide a PR to handle this if it's helpful.  Thanks!

**Comment by kaspergrubbe** [comment]
Might be a good idea to make Andrea Mazzoleni and the advpng team (If any such organisation exist) know about this. They might not be aware that other developers depend on i.

**Comment by jayroh** [comment]
That's a good idea. I'll see if I can find a good channel to report it over to him.

**Comment by jayroh** [comment]
For what it's worth - this _also_ happens with the version installed from homebrew

**Comment by kaspergrubbe** [comment]
Yes, I can also verify your finding from the Homebrew version.

```bash
$ advpng
advancecomp vnone by Andrea Mazzoleni, http://www.advancemame.it
Usage: advpng [options] [FILES...]

Modes:
  -l, --list            List the content of the files
  -z, --recompress      Recompress the specified files
Options:
  -0, --shrink-store    Don't compress
  -1, --shrink-fast     Compress fast (zlib)
  -2, --shrink-normal   Compress normal (libdeflate)
  -3, --shrink-extra    Compress extra (7z)
  -4, --shrink-insane   Compress extreme (zopfli)
  -i N, --iter=N        Compress iterations
  -f, --force           Force the new file also if it's bigger
  -q, --quiet           Don't print on the console
  -h, --help            Help of the program
  -V, --version         Version of the program
```

But neither `-V` or `--version` reports the version:

```
$ advpng --version
advancecomp vnone by Andrea Mazzoleni, http://www.advancemame.it
$ advpng -V
advancecomp vnone by Andrea Mazzoleni, http://www.advancemame.it
```

The homebrew package version I have is version 2.1:

```
$ brew list --versions | grep advancecomp
advancecomp 2.1
```

**Comment by toy** [comment]
After checking source: [autover.sh](https://github.com/amadvance/advancecomp/blob/master/autover.sh) is responsible for getting version for `./configure` to put into a generated header, `.version` file is not there, so it relies on `git tags`. I presume something like absence of `git` binary is breaking the process of building ubuntu and homebrew packages and the version defaults to `none`.
It will be great if you can contact responsible teams or people about the issue. And I think they can understand if something can be improved in the configuration process of `advancecomp`.

I'll try to come up with some solution, although PR is always welcome.

**Comment by toy** [comment]
https://github.com/toy/image_optim/compare/versionless-advpng should fix the problem

**Comment by toy** [comment]
Wrong archive is fetched, it should be `https://github.com/amadvance/advancecomp/releases/download/v2.1/advancecomp-2.1.tar.gz`. The one that is used is archive of git repository which doesn't contain `.version` file, and the one I've linked is a release archive which I think is created from repository after running all `auto*` tools and running the script that generates `.version` file.

**Comment by jayroh** [comment]
> https://github.com/toy/image_optim/compare/versionless-advpng should fix the problem

This is a _much_ better diff than the one I put together! Will this make its way into `master`?

**Comment by kaspergrubbe** [comment]
@toy Nicely spotted, I will update the Homebrew package.

**Comment by jayroh** [comment]
@kaspergrubbe I have not had a chance to email @amadvance - but maybe he'll see this issue and chime in. I'll post something over on sourceforge.

Looking through everything found here I think this is as much a problem with the "package" maintainers as it is with the build process itself. If done _right_, it's fine, but there's a lot of wiggle room in there to get it wrong.

**Comment by jayroh** [comment]
Bug filed at the Ubuntu package bug tracker here: https://bugs.launchpad.net/ubuntu/+source/advancecomp/+bug/1797662

**Comment by toy** [comment]
Thank you both for handling changes in homebrew and ubuntu!
I'm going to merge the change and release new version.

**Comment by jayroh** [comment]
Excellent! Thank you so much @toy :)
