### ISSUE TITLE
Specify a temp directory for the temporary files

### ISSUE THREAD

**Issue by luboslives** [toy/image_optim#178]
Is there any way, using the CLI, to have the temporary files be created in an external temp directory?

I've tried some directory watching programs and they always pick up the temp files because they keep the same file extensions as the original images, so I have them kicking off the `image_optim` process unnecessarily every time they pick up new temp files.

Ideally I'd like an option like `--tempdir /my/temp/dir`, if it can't currently be achieved any other way.

**Comment by toy** [comment]
Probably you are talking about a temporary file that is created to atomically replace original. Processing related temp files are created in default/system temporary directory.
For atomic operation source and destination must be on the same device, that is why temporary file is created in the same directory.

From code I can see that for the case of default temporary directory residing on the same device as destination there can be an optimisation of not creating this last temporary file. Then default temporary directory can be changed using `TMPDIR` environment variable.
Also probably changing temporary file extension to something like `.tmp` could help.

**Comment by luboslives** [comment]
@toy For some reason, image_optim will not use my temp directories (both on my Mac and on a VPS). I know this because I run it through a file watcher, and it shows me the temporary files being created in the same directory as the originals, and because I run it alongside ImageMagick to create webp duplicates. ImageMagick will obey the $TMPDIR I set right before running both commands – it will show it being used in the printout in verbose mode.

I thought maybe I had stumbled onto something with [this restriction set by Ruby](https://stackoverflow.com/questions/21117878/ruby-could-not-find-a-temporary-directory/31182540#31182540), but setting `chmod +t mytempdir` did not change the behaviour.

I don't know anything about Ruby but it seems you have `tmpdir` & `temp_dir` logic inside [/spec/image_optim/bin_resolver_spec.rb](https://github.com/toy/image_optim/blob/9aa7ea91446964dd3ac711e6a08a5d567f03d21c/spec/image_optim/bin_resolver_spec.rb#L133). As far as I can tell it should be pulling the value from the environment?

**Comment by toy** [comment]
I've added few changes and an entry to readme about changing temporary directory, would be great if you can try version from [less-tempfiles branch](https://github.com/toy/image_optim/compare/less-tempfiles).

**Comment by luboslives** [comment]
@toy I grabbed it and tried it out, but it looks like the bin itself is still an old version (so I get the same results). Do you or I have to build/make it? I'm not familiar with how that would work with Ruby 😊

**Comment by toy** [comment]
Sure :)
If it is ok to replace installed gem:
```shell
cd path-to-checkout-of-image_optim
gem build image_optim.gemspec
gem install image_optim-*.gem
image_optim ARGUMENTS_HERE
```
Afterwards you can run `gem uninstall image_optim` to remove it.

Or just running directly without installing:
```shell
cd path-to-checkout-of-image_optim
ruby -I lib bin/image_optim ARGUMENTS_HERE
# or without cd
ruby -I path-to-checkout-of-image_optim/lib path-to-checkout-of-image_optim/bin/image_optim ARGUMENTS_HERE
```

**Comment by luboslives** [comment]
It seems to be working correctly! Nothing strange to report – no temp files being created in the watched/original directory.

**Comment by toy** [comment]
Great, I'll merge it then
