### ISSUE TITLE
jpegoptim worker didn't strip comment

### ISSUE THREAD

**Issue by NaturalHokke** [toy/image_optim#188]
comment removal option is `jpegoptim: { strip: [:comments] }`
but jpegoptim's option is `--strip-com`

**Comment by toy** [comment]
Thank you for reporting, you completely right it should be just `com`.
So currently it is not possible to add `--strip-com` as using `jpegoptim: { strip: [:comments] }` will make jpegoptim warn and ignore the option and using `jpegoptim: { strip: [:com] } ` will cause a warning from the gem and will not add the switch.
https://github.com/toy/image_optim/compare/jpegoptim-update-marker-list should fix this.

**Comment by toy** [comment]
Released as part of v0.28.0
