### ISSUE TITLE
Integration with Rails asset pipeline as sprocket preprocessor

### ISSUE THREAD

**Issue by kristianmandrup** [toy/image_optim#2]
Check out this article :)

http://psionides.eu/2012/05/06/extending-asset-pipeline-with-custom-preprocessors/

``` ruby
class RootUrlPreprocessor < Sprockets::Processor
  def evaluate(context, locals)
    data.gsub(%r"\bHOSTNAME\b", "myserver.com")
  end
end
```

The context is an instance of Sprockets::Context; you can use it to e.g. read the current file’s path or content type, generate paths to asset files or access asset pipeline configuration. You also have access to several asset helpers from ActionView, like javascript_include_tag, image_tag etc.

http://rubydoc.info/gems/sprockets/2.0.3/Sprockets/Context

I think you would need fx `content_type` and somehow access the full path of the asset and run it through image_optim.

``` ruby
# in config/initializers/sprockets.rb
Rails.application.assets.register_preprocessor('application/javascript',
                                               RootUrlPreprocessor)
```

Just found an example here: https://github.com/botandrose/sprockets-image_compressor

Maybe you could join forces ;)

Sweet and simple! Yeah :)

**Comment by ghostropic** [comment]
Hey @toy 
I'm attempting to get [image_optim_pack](https://github.com/toy/image_optim_pack) pushed to Heroku. I tried using @mooktakim's build pack but fails while precompiling assets. Do you know of any other methods of getting your bin pack to build on Heroku?

**Comment by toy** [comment]
@ghostropic 
Do I understand right that `image_optim_pack` itself also doesn't work? Can you share errors?
One way to get binaries is to build them using Makefile from that gem.
Maybe it is also better to move this to a separate issue for that project.

**Comment by ghostropic** [comment]
@toy Sorry for the confusion. Image_optim_pack does work locally, but isn't useful to me unless I can get it working on Heroku, so I thought i'd ask if you had any leads on a build pack.  I suppose my only option though is to learn to write my own.

**Comment by toy** [comment]
@ghostropic Ah no, I understood you, but the questions were confusing. As I understand heroku gives you ubuntu servers and `image_optim_pack` should work on ubuntu. So does it not work on heroku and which errors do you get? And one way to get binaries is to use `make` on machine you are targeting, so on heroku instance.

**Comment by toy** [comment]
@ghostropic As there was already a heroku app to check versions, I've added there a very basic upload with optimisation for checking if everything works, and it seems it does: https://iopack.herokuapp.com/
