### ISSUE TITLE
Ruby 3.2.0 / Rails 7.0.4 invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by jasonfine** [toy/image_optim#205]
```Loading development environment (Rails 7.0.4)
irb(main):001:0> image_optim = ::ImageOptim.new
/usr/local/bundle/gems/image_optim-0.31.2/lib/image_optim/bin_resolver/bin.rb:124:in `[]': invalid byte sequence in UTF-8 (ArgumentError)

          date_str = capture("#{escaped_path} 2>&1")[date_regexp]
                                                     ^^^^^^^^^^^
irb(main):002:0>

**Comment by toy** [comment]
From the error looks like running `pngout 2>&1` in your environment gives a string that can't be converted to UTF-8.
What does running `` `pngout 2>&1` `` output and what is the encoding of the string?
And environment questions:
Is it dependant on ruby version and presence of rails?
Is it plain `irb`, `rails console` or something else?
Something special about the environment?

**Comment by jasonfine** [comment]
> What does running `pngout 2>&1` output and what is the encoding of the string?

Sorry - where should i run this command?

> And environment questions:
> Is it dependant on ruby version and presence of rails?

This started happening after upgrading Ruby 3.1 to 3.2, and yes this is in the context of a Rails 7.0.4 app.

> Is it plain irb, rails console or something else?

Rails console

> Something special about the environment?

Using Docker

**Comment by toy** [comment]
> Sorry - where should i run this command?

In the same console, as `ImageOptim.new`

> Using Docker

Would you be able to create minimal reproducible example then?

**Comment by jasonfine** [comment]
Upon closer inspection, i think this is due to missing binaries.

Thanks for your time
