### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Arcovion** [toy/image_optim#24]
Would be really nice to have this in windows, all the binaries exist for windows in some form.
Currently I tried setting `line 47` of `bin_resolver.rb` to true and now all I get is `The system cannot find the path specified.` with no traceroute or easy way to debug it.
It's probably because it can't find the .exe files even though they are in `PATH` and `gems\image_optim-0.10.0\vendor`.
Also `bin_resolver.rb` uses symlinks which are not supported in ruby on windows.

Maybe it's possible to extensively patch that one file and fix everything?
If not then I guess windows support may never happen, but I accept that. :cry:

**Comment by Arcovion** [comment]
Closing, having all the binaries in `image_optim_pack` is much better and not something you can really replicate on Windows without a lot of effort.

**Comment by toy** [comment]
Should work on windows, have a look at ae01fefdaac6bce937ca6c22b7f305c03dc091cd
