### ISSUE TITLE
`pngout` not found, linux

### ISSUE THREAD

**Issue by mperice** [toy/image_optim#39]
Image_optim v 0.11.1 causes:

rake aborted!
`pngout` not found

on a debian machine, all packages (advancecomp gifsicle jhead jpegoptim libjpeg-progs optipng pngcrush) are installed.

**Comment by avinashdvv** [comment]
pngout worker: `pngout` not found; please provide proper binary or disable this worker (--no-pngout argument or `:pngout => false` through options) on ------rake db:migrate----- 
i am getting this error , how can i disable it 
  @toy

**Comment by toy** [comment]
@avinashdvv You either need to make `pngout` [available in path](/toy/image_optim#pngout-installation-optional) or disable the worker in [yml config](/toy/image_optim#configuration) or through [options to image_optim initialiser](/toy/image_optim_rails#usage). Which version are you using?
