### ISSUE TITLE
How to make Image Optim work with in memory object - Ruby StringIO Objects

### ISSUE THREAD

**Issue by chirag7jain** [toy/image_optim#80]

**Comment by toy** [comment]
@chirag7jain Currently for in memory objects there is a method `optimize_image_data` to optimize data provided as string. So for `StringIO` if you want to get another `StringIO` you can do something like this:
```
out = ImageOptim.optimize_image_data(io.string)
io_out = out && StringIO.new(out)
```

**Comment by chirag7jain** [comment]
@toy thanks
