### ISSUE TITLE
Run twice?

### ISSUE THREAD

**Issue by tejasmanohar** [toy/image_optim#82]
If I run image_optim twice over an image, is that to my benefit by any means?

**Comment by toy** [comment]
In vast majority of cases no. Rarely I saw few more bytes shaven on second run from some files, but normally second run will be useless.
I've thought about adding "ultimate" mode (as part of adding compression levels) which will apply all workers in all possible orders repeatedly to find the best possible compression, though such mode will be very time consuming.

**Comment by tejasmanohar** [comment]
@toy ah, alright. so having this as a rake task to run over all my images before deploy, is fine?

**Comment by toy** [comment]
@tejasmanohar Yes, running once will be sufficient. Also if using image_optim through railtie you will have an advantage of optimised images been cached.

**Comment by tejasmanohar** [comment]
@toy using jekyll, not rails. no downsides of running twice, correct? because i was planning to add this function to the build rake task which means the same files could go through this process multiple times

**Comment by toy** [comment]
@tejasmanohar No downsides except time, I've just created an issue about caching #83.
