### ISSUE TITLE
Add option to cache results?

### ISSUE THREAD

**Issue by toy** [toy/image_optim#83]
`--cache=dir`/`cache: 'dir'`
Save result of optimization by src digest + options digest

**Comment by tejasmanohar** [comment]
+1

**Comment by gpakosz** [comment]
Well, I believe you would need: src image digest + options digest + binaries digest to make sure upgrading binaries triggers cache eviction.

**Comment by toy** [comment]
@gpakosz Using binaries digest depends on the assumption about the purpose of cache: without binaries digest, cache will be an efficient time saver and with binaries digest it may become much less efficient, though will probably save few or more bytes from time to time.

**Comment by gpakosz** [comment]
@toy well it's a matter of reproducibility I would say: an optimize image is the product of source image + optimizers versions + options. I would argue binaries deployed change rarely balancing your "much less efficient" point of view.

**Comment by toy** [comment]
@gpakosz It will be often if binaries will be updated regularly — check https://github.com/toy/image_optim_pack/releases. Also cache can be removed manually. And caching can have an option to switch on/off binaries digest.

**Comment by gpakosz** [comment]
An option to cache upon binaries digest is indeed a good idea
