### ISSUE TITLE
Output to stdout instead of stderr?

### ISSUE THREAD

**Issue by nwtn** [toy/image_optim#84]
Is there any reason that verbose status info is output in stderr instead of stdout? I had a script that was watching for output on stderr and counting it as actual error data; this tripped it up.

**Comment by toy** [comment]
Stderr is for error messages and diagnostic information, so program output and diagnostic messages are separated to stdout and stderr. Not the perfect example, but check `curl -vvv https://github.com`. In most cases it is better to rely on program exit code.

**Comment by nwtn** [comment]
I did mod the script to look at exit code, so that got around the problem. I guess I just didn't really consider this output to be diagnostic information, but I suppose that makes sense.
