### ISSUE TITLE
Update Gratipay so I can continue to support

### ISSUE THREAD

**Issue by kaspergrubbe** [toy/image_optim#86]
Hello @toy !

I wanted to increase the amount of money that I give on Gratipay, and send them your way.

Preferably this should have been an email, but I couldn't find one. Gratipay are making changes: https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077 

Long story short: You need to create a ImageOptim team so I can continue my support.

Let me know if you go with something else than Gratipay so I can move my payments over there.

Have a nice weekend,
- Kasper

**Comment by toy** [comment]
Thanks for support Kasper!
Gratipay is in strange state now, but I've created [the team](https://gratipay.com/image-optim/) for `image_optim` and it is awaiting review, probably on Monday.

**Comment by toy** [comment]
Review process took longer than I expected, but finally the team is there — https://gratipay.com/image-optim/. And I really hope to return to development as soon as I settle down in new place.

**Comment by kaspergrubbe** [comment]
@toy Thank you for your update and your hard work :+1:
