### ISSUE TITLE
Status FreeBSD

### ISSUE THREAD

**Issue by ghost** [toy/image_optim#89]
# [image_optim](https://github.com/toy/image_optim) for FreeBSD

## MISSING PACKAGES: [jpeg-recompress](https://github.com/danielgtaylor/jpeg-archive), [pngout](http://www.jonof.id.au/kenutils)

- - -

#### **OK** - [zopfli](https://github.com/google/zopfli)

`pkg install zopfli` [zopfli @ FreeBSD ports](http://svnweb.freebsd.org/ports/head/archivers/zopfli/)

- - -

#### **OK** - [gifsicle](http://www.lcdf.org/gifsicle/)

`pkg install gifsicle` [gifsicle @ FreeBSD ports](http://svnweb.freebsd.org/ports/head/graphics/gifsicle/)

- - -

#### **OK** - [jhead](http://www.sentex.net/~mwandel/jhead/)

`pkg install jhead` [jhead @ FreeBSD ports](http://svnweb.freebsd.org/ports/head/graphics/jhead/)

- - -

#### **OK** - [jpegoptim](https://github.com/tjko/jpegoptim)

`pkg install jpegoptim` [jpegoptim @ FreeBSD ports](http://svnweb.freebsd.org/ports/head/graphics/jpegoptim/)

- - -

#### **OK** - [jpeg-recompress](https://github.com/danielgtaylor/jpeg-archive)

NO SUCH PACKAGE: `pkg install jpeg-recompress`

Recent fix: https://github.com/danielgtaylor/jpeg-archive/pull/28

- - -

#### **OK** - [mozjpeg](https://github.com/mozilla/mozjpeg)

`pkg install mozjpeg` [mozjpeg@ FreeBSD ports](http://svnweb.freebsd.org/ports/head/graphics/mozjpeg/)

**NOTE**: Might require you to uninstall tools that have IJG's [jpeg8_6](http://svnweb.freebsd.org/ports/head/graphics/jpeg/) as dependency, but you can always reinstall them afterwards.

- - -

#### **OK** - [jpegtran](http://www.ijg.org/)

`pkg install jpeg` [jpeg @ FreeBSD ports](http://svnweb.freebsd.org/ports/head/graphics/jpeg/)

- - -

#### **OK** - [optipng](http://optipng.sourceforge.net/)

`pkg install optipng` [optipng @ FreeBSD ports](http://svnweb.freebsd.org/ports/head/graphics/optipng/)

- - -

#### **OK** - [pngcrush](http://pmt.sourceforge.net/pngcrush/)

`pkg install pngcrush` [pngcrush @ FreeBSD ports](http://svnweb.freebsd.org/ports/head/graphics/pngcrush/)

- - -

#### **OK** - [pngout](http://www.jonof.id.au/kenutils)

NO SUCH PACKAGE: `pkg install pngout`

```
# uname -p
amd64
# wget http://static.jonof.id.au/dl/kenutils/pngout-20150319-bsd.tar.gz && tar xvzf pngout-20150319-bsd.tar.gz && ./amd64/pngout
```

- - -

#### **OK** - [pngquant](https://github.com/pornel/pngquant)

`pkg install pngquant` [pngquant @ FreeBSD ports](http://svnweb.freebsd.org/ports/head/graphics/pngquant/)

- - -

#### **OK** - [svgo](https://github.com/svg/svgo)

NO SUCH PACKAGE: `pkg install svgo`

`npm install svgo` [svgo @ npmjs](https://www.npmjs.com/package/svgo)

**Comment by toy** [comment]
Wow, interesting! I'll try get back to this soon.
Also I want to add FreeBSD support to [image_optim_pack](https://github.com/toy/image_optim_pack), which will make things even easier. Could you help to configure vagrant boxes for that?

**Comment by murkfletcher** [comment]
Absolutely! As long as we can support OpenBSD support as well.

Some of the current sentiment: https://news.ycombinator.com/item?id=9916005

**Comment by murkfletcher** [comment]
image_optim should now work for FreeBSD:

https://github.com/danielgtaylor/jpeg-archive/pull/28

**Comment by toy** [comment]
Great! And then it should be easier to add it to `image_optim_pack`.

OpenBSD — sure! About Vargrant — I think experience with FreeBSD and OpenBSD is needed more than with Vagrant.

**Comment by murkfletcher** [comment]
Reopening due to `jpeg-recompress`.
