### ISSUE TITLE
Package pngcrush is not available, but is referred to by another package.

### ISSUE THREAD

**Issue by confile** [toy/image_optim#93]
I tried: 

```
apt-get install -y advancecomp gifsicle jhead jpegoptim libjpeg-progs optipng pngcrush pngquant
```
and the get the following error: 

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package pngcrush is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package advancecomp
E: Unable to locate package gifsicle
E: Unable to locate package jhead
E: Unable to locate package jpegoptim
E: Unable to locate package libjpeg-progs
E: Unable to locate package optipng
E: Package 'pngcrush' has no installation candidate
E: Unable to locate package pngquant
```

**Comment by toy** [comment]
Please tell about your environment.

First suggestion from stackexchange about «Unable to locate package» is to run `sudo apt-get update`. Maybe it will resolve the `pngcrush` error to. Also you may want to try [image_optim_pack](https://github.com/toy/image_optim_pack).

**Comment by confile** [comment]
I use Ubuntu 12.04 LTS

**Comment by toy** [comment]
I was able to reproduce the same output after removing package index files (using `sudo rm -r /var/lib/apt/lists/*`) in fresh ubuntu precise in vagrant. After running then `sudo apt-get update` and `sudo apt-get install …` all packages were installed successfully.

**Comment by toy** [comment]
Any progress on this?

**Comment by confile** [comment]
Done. Thank you.
