### ISSUE TITLE
How to install pngout on osx 10.10 and ubuntu?

### ISSUE THREAD

**Issue by steffimueller** [toy/image_optim#94]
I found the link but I have no idea what to do there. The page is so crowded. Could you pleas give a little help? 

Thank you.

**Comment by toy** [comment]
You need to download and unpack the archive with MacOSX binary ([current version](http://static.jonof.id.au/dl/kenutils/pngout-20150319-darwin.tar.gz)). I did not give a direct link in the readme as it can be only a link to specific version, so there will be problems if new version of pngout will be released.

**Comment by toy** [comment]
Did you find the binary?

**Comment by confile** [comment]
@toy I have the same problem. Could you please explain how to install it on OSX?

**Comment by toy** [comment]
@confile Download the archive, unpack it and put the `pngout` binary somewhere in `PATH`.

**Comment by confile** [comment]
Could you please post the link?

**Comment by toy** [comment]
@confile It is «[current version](http://static.jonof.id.au/dl/kenutils/pngout-20150319-darwin.tar.gz)» in my first reply for this issue

**Comment by confile** [comment]
got it thank you
