### ISSUE TITLE
The ImageOptim app for Mac OS X optimizes better than the gem

### ISSUE THREAD

**Issue by sergey-alekseev** [toy/image_optim#96]
Hey, Ivan! Thanks for the :gem:.

Due to your gem I found the [*ImageOptim app*](https://imageoptim.com/) and tried it first. The app is just great :heart:
After that I've started using the [*image_optim gem*](https://github.com/toy/image_optim) and encountered *a weaker optimization*. 
Example files: 
----
* http://i.imgur.com/UXkqvAO.png (118,049 bytes initially; 113,710 bytes after the *image_optim gem*) – http://i.imgur.com/BO3EkjX.png (112,355 bytes after the *ImageOptim app*)
* http://i.imgur.com/8m8tSKG.png (7,189 bytes initially; the same after the *image_optim gem*) – http://i.imgur.com/RJhFJkF.png (7,100 bytes after the *ImageOptim app*)
* http://i.imgur.com/H4vwBSK.jpg (158,163 bytes initially; 149,239 bytes after the *image_optim gem*) – http://i.imgur.com/PQNcSrW.jpg (147,383 bytes after the *ImageOptim app*)

I can provide more example files if necessary. Those were first 3 images I tried to compress with the *image_optim gem*.

What I did to use the gem:  
----
* Added `gem 'image_optim', '~> 0.21.0'` and `gem 'image_optim_pack', '~> 0.2.1.20150802'` to `Gemfile` and bundle installed them
* Installed binaries with `brew install advancecomp gifsicle jhead jpegoptim jpeg optipng pngcrush pngquant` (ran `brew update` first) and optionally installed `svgo` + `pngout` – those installations probably had no effect

Questions
----
Is that expected? How can I optimize with help of the *image_optim gem* as well as with help of the *ImageOptim app*?

**Comment by toy** [comment]
I see right away that I need to update the `README.markdown` as when using `image_optim_pack` you don't need to install anything except `svgo` and `pngout`.

`image_optim` is expected to be as good as possible. Asking if it is expected for `ImageOptim` to optimise better than `image_optim` is a very strange question. You can optimise using both tools and there is a [cli for `ImageOptim`](https://imageoptim.com/command-line.html). And everyone is very welcome to contribute.

**Comment by feliperaul** [comment]
@toy First of all, thanks for the awesome work in this gem!

I agree with @sergey-alekseev about the relevance of this question, since I ended up here searching if someone had asked this previously before I made a duplicate question.

In my tests, ImageOptim.app can optimize 30% further then the gem with the same configuration. I can provide some detailed tests and files if you need me to.

The thing is, since ImageOptim.app is open source and uses open source libs to do its magic (https://github.com/ImageOptim/ImageOptim), namely `PNGOUT, AdvPNG, Pngcrush, OxiPNG, JpegOptim, MozJPEG, Gifsicle, SVGO, and svgcleaner`, I think it's reasonable to expect that this gem could match the optimization of the app, because both could be using the same libs! It also helps that the names are the same (I know it's a coincidence :) )

Since the differences are considerable (like I said, extra 30% in our tests), would you consider re-opening this issue so we could dig further why the difference is so large?

**Comment by kaspergrubbe** [comment]
@feliperaul Maybe someone could re-run the numbers with a public test-case to see how far the optimizations done by both projects are from each other. I also think we should include the settings from ImageOptim in here.

**Comment by feliperaul** [comment]
Totally agree. Will do as soon as I have some time.

**Comment by toy** [comment]
@feliperaul Same name is not a coincidence, it is in readme, `image_optim` is "Based on ImageOptim.app" ;)

Numbers are the best. Running both tools on original three images gives following:

tool  |  original  |  image_optim  |  ImageOptim
----  |  --------  |  -----------  |  ----------
8m8tSKG.png  |  [7,189 B](https://user-images.githubusercontent.com/18144/51077493-c1e6f900-16a7-11e9-933a-db9c5e8c7df1.png)  |  [7,122 B](https://user-images.githubusercontent.com/18144/51077505-dc20d700-16a7-11e9-90d0-9543e309673d.png)  |  [7,118 B](https://user-images.githubusercontent.com/18144/51077512-f35fc480-16a7-11e9-9eed-e3e8d832ab92.png)
H4vwBSK.jpg  |  [158,163 B](https://user-images.githubusercontent.com/18144/51077496-c6131680-16a7-11e9-86a1-1331f9c3b002.jpg)  |  [147,405 B](https://user-images.githubusercontent.com/18144/51077506-dfb45e00-16a7-11e9-910e-851874e01777.jpg)  |  [147,401 B](https://user-images.githubusercontent.com/18144/51077514-f8247880-16a7-11e9-8ed8-324d62630b57.jpg)
UXkqvAO.png  |  [118,049 B](https://user-images.githubusercontent.com/18144/51077497-c9a69d80-16a7-11e9-905b-bacc148fe002.png)  |  [112,377 B](https://user-images.githubusercontent.com/18144/51077508-e347e500-16a7-11e9-8215-f1f0381d1406.png)  |  [112,373 B](https://user-images.githubusercontent.com/18144/51077517-ff4b8680-16a7-11e9-87d8-efeaad4f2580.png)

so ImageOptim on this images removes 4 bytes more than image_optim (a bit weird that the difference is identical even if they are of different formats and better to find where does it come from).

Anyway better to find examples of images that are optimised considerably worse and see how to improve that. Comparing optimisation efficiency can be done using a simple script, or maybe a tool from JamieMason will make it simpler, there were few iterations of it: http://toy.github.io/ImageOptim-CLI/, http://jamiemason.github.io/image-optimisation-tools-comparison/, https://foldleft.io/image-tools/

I think it is better to open a new issue with examples of images that are optimised worse.

**Comment by feliperaul** [comment]
I could swear I saw a 30% difference last friday.  But when I was trying to put together a test case for this, I got these results (repeatedly):

Original: 4.6MB
ImageOptim Mac 1.8.8: 3.5MB with lossy JPEG 93%
image_optim gem: **2.7MB** with 
```
    jpegoptim: {
        allow_lossy: true,
        max_quality: 93
      }
```

So ... only thing I have to say as of now is thanks for the great work on this gem.

**Comment by toy** [comment]
@feliperaul I'm glad that the gem is helpful :)

Do you remember if 30% difference was for lossy or lossless optimisation?
For lossy jpeg optimisation biggest effect is brought by `jpegrecompress`, to properly compare lossy optimisation measure of quality loss is needed.
